In [ ]:
import numpy as np

#import library untuk keterangan waktu
from datetime import date

In [ ]:
Mahasiswa = ["Nama: Indah Hairunisah", "NIM: 2022071025", "Prodi: Informatika", "Matkul: Desain Analisis dan Algoritma", "Nama Universitas: Universitas Pembangunan Jaya", "Tanggal hari ini: " + str(date.today())]

for i in Mahasiswa:
  print(i)

Nama: Indah Hairunisah
NIM: 2022071025
Prodi: Informatika
Matkul: Desain Analisis dan Algoritma
Nama Universitas: Universitas Pembangunan Jaya
Tanggal hari ini: 2023-09-13


In [ ]:
#ini belajar list
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[-1]

'Yellow'

In [ ]:
#Memanggil nim  dalam list mahasiswa
print(Mahasiswa[0])
print(Mahasiswa[1])
print(Mahasiswa[2])
print(Mahasiswa[3])
print(Mahasiswa[4])
print(Mahasiswa[4])

Nama: Indah Hairunisah
NIM: 2022071025
Prodi: Informatika
Matkul: Desain Analisis dan Algoritma
Nama Universitas: Universitas Pembangunan Jaya
Nama Universitas: Universitas Pembangunan Jaya


In [ ]:
#list slicing
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']

print(bin_colors[0:2])
print(bin_colors[0:-1])
print(bin_colors[:4])
print(bin_colors[-2:])


['Red', 'Green']
['Red', 'Green', 'Blue']
['Red', 'Green', 'Blue', 'Yellow']
['Blue', 'Yellow']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
  print (aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
#data ini ngambil dari atas, bisa juga gausah ditulis ulang di blok kode ini
Mahasiswa = ["Nama: Indah Hairunisah", "NIM: " + str(2022071025), "Prodi: Informatika", "Matkul: Desain Analisis dan Algoritma", "Nama Universitas: Universitas Pembangunan Jaya", "Tanggal hari ini: " + str(date.today())]
#Note: untuk angka numerik tidak bisa lngsung ditambahkan dengan string, jadi harus ditambahkan str(baru diisi angka numerik), baru deh bisa ditabahkan dengan string

for aku in Mahasiswa:
  print (aku + " ")


Nama: Indah Hairunisah 
NIM: 2022071025 
Prodi: Informatika 
Matkul: Desain Analisis dan Algoritma 
Nama Universitas: Universitas Pembangunan Jaya 
Tanggal hari ini: 2023-09-13 


In [ ]:
for UPJ in Mahasiswa:
  print ("UPJ " , UPJ)

  #Notes:
  #kalo pake , itu bisa semua tipe data
  #tapi kalo pake + dia harus tipe data string, kalo mau ditambah tipe data lain(numerik misalnya) harus pake kode tipe datanya. misal str(NIM)
  #print ("UPJ " + UPJ)

UPJ  Nama: Indah Hairunisah
UPJ  NIM: 2022071025
UPJ  Prodi: Informatika
UPJ  Matkul: Desain Analisis dan Algoritma
UPJ  Nama Universitas: Universitas Pembangunan Jaya
UPJ  Tanggal hari ini: 2023-09-13


In [ ]:
#Berbeda dengan list, tuple adalah struktur data yang tidak dapat diubah (read-only). Tuple terdiri dari beberapa elemen yang dikelilingi oleh ( ).
#pada struktur data tuples bisa dimasukan boolean, dictionary, dan list juga, misal:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]
'Green'
bin_colors[2:]
('Blue', 'Yellow')

('Blue', 'Yellow')

In [ ]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
UPJ[0:]

('Universitas', 'Pembangunan', 'Jaya', 'Jaya')

In [ ]:
hariAwal = ("senin","selasa","rabu")
hariAkhir = ("kamis","jumat","sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [ ]:
#Nested Tuples
nested_tuple = ( 100, [200, 400, 600], 300,  [400, 800])
nested_tuple[2]

300

In [ ]:
#Struktur Data dalam Python: Dictionary
bin_colors = {"manual_color":"Yellow", "approved_color":"Green", "refused_color":"Red"}
print (bin_colors)


{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
#Struktur Data dalam Python: Dictionary
#Untuk mengambil nilai yang terkait dengan key, fungsi get dapat digunakan atau key dapat digunakan sebagai indeks:
bin_colors['approved_color']


'Green'

In [ ]:
bin_colors['approved_color'],'Green'


('Green', 'Green')

In [ ]:
bin_colors['approved_color']="Purple"
print(bin_colors)
{'manual_color': 'Yellow', 'approved_color': 'Purple',
'refused_color': 'Red'}


{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}

In [ ]:
#ini dictionary
DataMahasiswa2 = {'Nama':'Indah Hairunsah', 'NIM': 2022071025, 'Prodi':'Informatika', 'Universitas':'UPJ'}
print (DataMahasiswa2)

{'Nama': 'Indah Hairunsah', 'NIM': 2022071025, 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
acak = (True, {'name' : 'depotkode','status': 'alive'}, [1,2,3])
print(acak)

(True, {'name': 'depotkode', 'status': 'alive'}, [1, 2, 3])


In [ ]:
#Set didefinisikan sebagai kumpulan elemen yang dapat berbeda jenis. Elemen-elemen diapit di dalam {}.
green = {'grass', 'leaves'}
print(green)
{'grass', 'leaves'}

{'grass', 'leaves'}


{'grass', 'leaves'}

In [ ]:
#Karakteristik yang menentukan dari suatu set adalah bahwa ia hanya menyimpan nilai yang berbeda dari setiap elemen. Jika coba menambahkan elemen redundan lainnya, itu akan mengabaikannya
green = {'grass', 'leaves','leaves'}
print(green)
{'grass', 'leaves'}

In [ ]:
#Slide 26
#Inisiasi Set
set_01 = {4,5,6,2}
print(set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])
print(type(set_02))
print(set_03)

{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}


In [ ]:
#slide 27
#Set merupakan struktur data yang tidak memiliki urutan atau index. Sehingga tidak dapat mengakses anggota dengan menggunakan index seperti pada list atau tuple
#Karena tidak dapat memiliki index, maka untuk menghapus anggota set menggunakan dua metode yaitu discard() dan remove()

set_01 = {4,5,6,2}
print(set_03[1])
#TypeError: 'set' object does not support indexing


TypeError: ignored

In [ ]:
#slide 28
#Menambah anggota set dapat dilakukan dengan menggunakan metode add() yang digunakan untuk menambahkan hanya satu anggota pada set.

set_04 = {2,3,4,5,6}
set_04.add(1)
print(set_04)

{1, 2, 3, 4, 5, 6}


In [ ]:
#Dikarenakan set adalah struktur data yang tidak memiliki index sehingga tidak dapat mengubah secara langsung, namun dengan cara menghapus lalu menambahkan anggota yang diinginkan. Contoh mengganti nilai 4 menjadi 10 sebagai berikut:

set_04= {1, 2, 3, 4, 5, 6, 7, 8}
set_04.discard(4)#hapus nilai 4
print(set_04)

set_04.add(10) #menambahkan nilai 10
print(set_04)
{1, 2, 3, 5, 6, 7, 8, 10}#

{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


{1, 2, 3, 5, 6, 7, 8, 10}

In [ ]:
#Union adalah saat kita menggabungkan semua anggota set. Mempersiapkan dua set yaitu Set A dan Set B sebagai berikut:

set_A = {1,2,3,4}
set_B = {3,4,5,6}
print(set_A|set_B)
print(set_A.union(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [ ]:
#Intersection adalah irisan, dimana kita mencari nilai irisan dari dua buah set.
#Intersection dapat dilakukan dengan menggunakan tanda “&” atau menggunakan metode intersection()

print(set_A & set_B)
print(set_A.intersection(set_B))

In [ ]:
#Difference adalah operasi saat kita mencari perbedaan anggota dari dua buah set atau lebih.
#Difference dapat dilakukan dengan menggunakan tanda “-” atau menggunakan metode difference().

#A - B
set_A - set_B
print(set_A - set_B)
print(set_A.difference(set_B))

#B - A
set_B - set_A
print(set_B - set_A)
print(set_B.difference(set_A))

{1, 2}
{1, 2}
{5, 6}
{5, 6}


In [ ]:
#Symmetric Difference adalah semua anggota pada set A dan B dikurangi dengan anggota yang berada pada dua set tersebut.
#symmetric difference dapat dilakukan dengan menggunakan tanda “^” atau menggunakan metode symmetric_difference().

print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [ ]:
yellow = {'dandelions', 'leaves','fire hydrants'}
red = {'fire hydrants', 'blood', 'leaves', 'rose'}
print (yellow|red)
print (yellow&red)

In [ ]:
#DataFrame adalah struktur data yang digunakan untuk menyimpan data tabular yang tersedia dalam paket pandas Python. Ini adalah salah satu struktur data terpenting untuk algoritme dan digunakan untuk memproses data terstruktur tradisional.
import pandas as pd
df = pd.DataFrame([
['1', 'Fares', 32, True],
['2', 'Elena', 23, False],
['3', 'Steven', 40, True]])

#ini untuk menampilkan
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df


id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[['name', 'age']]


name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[:,3]


0     True
1    False
2     True
Name: decision, dtype: bool

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [ ]:
data = {'satu': [1,1,1,1,1],
        'dua' : [2,2,2,2,2],
        'tiga': [3,3,3,3,3]}

df = pd.DataFrame(data, index=['a','b','c','d','e'])

df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [ ]:
df = pd.DataFrame([['1', 'Informatika', 50, 30, 20],
                   ['2', 'Sistem Informasi', 55, 30, 25],
                   ['3', 'Teknik Sipil', 40, 30, 10]])

df.columns = ['no', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

no             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [ ]:
#Matriks adalah struktur data dua dimensi dengan jumlah kolom dan baris yang tetap. Setiap elemen matriks dapat disebut dengan kolom dan barisnya.
myMatrix = np.array([
                    [11, 12, 13],
                    [21, 22, 23],
                    [31, 32, 33]])
print (myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
import numpy as np
matriksC = np.array([[1,2,3],
		     [4,5,6]])
print("Matriks C : ")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Tranpose Matriks C : ")
print(transpose_matriks)

Matriks C : 
[[1 2 3]
 [4 5 6]]
Tranpose Matriks C : 
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
myMatrix2 = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800],
])
print (f'Original Array:\n{myMatrix2}')
myMatrix2_transposed = myMatrix2.transpose()
print (f'Transposed Array:\n{myMatrix2_transposed}')

Original Array:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transposed Array:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
#Menggunakan list Python:
myVector = [22, 33, 44, 55]
print (myVector)
print (type(myVector))


[22, 33, 44, 55]
<class 'list'>


In [ ]:
myVector = np.array ([22, 33, 44, 55])
print (myVector)
print (type(myVector))

In [ ]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [ ]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())


4


In [ ]:
print(queue.dequeue())
print(queue.dequeue())

Blue
Yellow
